((cluster
   (node (name "node1")
         (tags "tag1")
         (ssh-hostname "2001:db8:0:1::1")
         (ssh-user "root")
         (ssh-command "ssh -i ~/.ssh/desmo_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"))
   (node (name "node2")
         (ssh-user "root")
         (ssh-hostname "2001:db8:0:1::2")
         (ssh-command "ssh -i ~/.ssh/desmo_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"))
   (node (name "node3")
         (ssh-user "root")
         (ssh-hostname "2001:db8:0:1::3")
         (ssh-command "ssh -i ~/.ssh/desmo_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null")))
 (service (name "service1")
          (port 80)
          (protocol "tcp")
          (requires-tag "tag1")))

