name: desmoctl

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Chicken
      run: apt update && apt install -y chicken-bin

    - name: Install dependencies
      run: make deps

    - name: Run tests
      run: make test
